# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 19:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотографія')),
                ('sex', models.CharField(choices=[('M', 'Чоловік'), ('W', 'Жінка')], max_length=1, verbose_name='Стать')),
                ('status', models.CharField(blank=True, max_length=140, null=True, verbose_name='Статус')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Розришений профіль')),
                ('location', models.CharField(blank=True, max_length=20, null=True, verbose_name='Місто')),
                ('fb_id', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
