# Generated by Django 2.0.2 on 2018-02-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180114_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name="Ім'я")),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Почта')),
                ('text', models.TextField(max_length=5000, null=True, verbose_name='Текст')),
                ('checked', models.BooleanField(default=False, verbose_name='Опрацьовано')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fb_id',
        ),
    ]
