# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0002_auto_20171112_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='signatures_left',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='petition',
            name='days_left',
            field=models.DurationField(verbose_name=4),
        ),
    ]
