# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0003_auto_20171112_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petition',
            old_name='signatures_left',
            new_name='signatures_needed',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='progress',
        ),
    ]
