# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0004_auto_20171112_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='answer',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
