# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0006_auto_20171112_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
    ]
