# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0007_petition_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='is_active',
        ),
        migrations.AddField(
            model_name='petition',
            name='status',
            field=models.CharField(choices=[('A', 'Збір підписів'), ('C', 'На розгляді'), ('W', 'З відповіддю'), ('R', 'Не пітримано')], default='A', max_length=3),
        ),
    ]
