# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0009_auto_20180106_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата підписання'),
            preserve_default=False,
        ),
    ]
