# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 20:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0010_signature_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='days_left',
            field=models.DurationField(default=datetime.timedelta(30)),
        ),
    ]
