# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 12:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0012_auto_20180106_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 24, 12, 43, 18, 858128)),
        ),
    ]
