# Generated by Django 2.0.1 on 2018-01-28 16:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petitions', '0013_auto_20180114_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petition_responder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petition',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petition',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petition_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='petition',
            name='signatures_needed',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='petition',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 27, 16, 35, 53, 449173)),
        ),
    ]
