# Generated by Django 2.0.1 on 2018-01-28 16:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0014_auto_20180128_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='signatures_needed',
        ),
        migrations.AlterField(
            model_name='petition',
            name='answer',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Відповідь'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petition_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата публікації'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petition_responder', to=settings.AUTH_USER_MODEL, verbose_name='Відповідач'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата відповіді'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Збір підписів'), ('CONSIDERATION', 'На розгляді'), ('ANSWERED', 'З відповіддю'), ('REJECTED', 'Не пітримано')], default='ACTIVE', max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='text',
            field=models.TextField(max_length=10000, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 27, 16, 44, 26, 191492), verbose_name='Кінцева дата'),
        ),
    ]
