# Generated by Django 2.0.1 on 2018-02-19 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0015_auto_20180128_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='answer',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Відповідь'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Збір підписів'), ('ON_CONSIDERATION', 'На розгляді'), ('ANSWERED', 'З відповіддю'), ('REJECTED', 'Не пітримано')], default='ACTIVE', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 10, 15, 9, 103370), verbose_name='Кінцева дата'),
        ),
    ]
