# Generated by Django 2.2.8 on 2021-01-20 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0017_auto_20180227_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 19, 16, 58, 52, 902051), verbose_name='Кінцева дата'),
        ),
    ]
